job('First-Maven-project-Via-DSL') {
	description("First Maven job generated by DSL on ${new Date()}")
	scm {
	   git ("https://github.com/trips1990/ValaxyTech_Java.git", "master")
	}
	triggers {
	   scm ('* * * * *')
	}
	steps {
	   maven('clean install package')
	}
	publishers {
		archiveArtifacts '**/*.war'
	}
}
