freeStyleJob('example') {
    description("First Maven job generated by DSL on ${new Date()}")
    scm {
        github('https://github.com/trips1990/ValaxyTech_Java.git', 'master')
    }
    triggers {
        scm ('* * * * *')
    }
    steps {
        maven('clean install package')
    }
    publishers {
	archiveArtifacts '**/*.war'    
}
}
